import json
import os
import re
import collections

LANGS = ['en', 'es', 'pt']
TEMPLATES_PATH = 'frontend/templates'
JS_TEMPLATES_PATH = 'frontend/www/js/omegaup'
BADGES_PATH = 'frontend/badges'

def _unescape(s):
    return s.replace('\\"', '"').replace('\\n', '\n')

def _pseudoloc(original):
    table = str.maketrans('elsot', '31507')
    tokens = re.split(r'(%\([a-zA-Z0-9_-]+\))', original)
    for i, token in enumerate(tokens):
        if token.startswith('%(') and token.endswith(')'):
            continue
        tokens[i] = token.translate(table)
    return f'({"".join(tokens)})'

def parse_lang_file(filename, lang, strings):
    if not os.path.exists(filename): return
    with open(filename, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or '=' not in line: continue
            try:
                key, value = re.compile(r'\s+=\s+').split(line, 1)
                match = re.compile(r'^"((?:[^"]|\\")*)"$').match(value)
                if match:
                    strings[key][lang] = match.group(1).replace(r'\"', '"')
            except ValueError:
                pass # Skip invalid lines

def add_badges_entries(strings):
    if not os.path.exists(BADGES_PATH): return
    aliases = [f.name for f in os.scandir(BADGES_PATH) if f.is_dir()]
    for alias in aliases:
        key_name = f'badge_{alias}_name'
        key_desc = f'badge_{alias}_description'
        filename = os.path.join(BADGES_PATH, alias, 'localizations.json')
        if os.path.exists(filename):
            with open(filename, 'r', encoding='utf-8') as f:
                contents = json.load(f)
                for lang in LANGS:
                    if lang in contents:
                        strings[key_name][lang] = contents[lang]['name']
                        strings[key_desc][lang] = contents[lang]['description']

def generate_sorted(lang, strings):
    result = []
    for key in sorted(strings.keys()):
        if lang in strings[key]:
            val = strings[key][lang].replace('"', r'\"')
            result.append(f'{key} = "{val}"\n')
    return ''.join(result)

def generate_typescript(lang, strings):
    result = []
    result.append('// generated by stuff/i18n.py. DO NOT EDIT.')
    result.append('const translations: { [key: string]: string; } = {')
    for key in sorted(strings.keys()):
        if lang in strings[key]:
            result.append(f'  {key}: {json.dumps(_unescape(strings[key][lang]))},')
    result.append('};\n')
    result.append('export {translations as default};')
    return '\n'.join(result)

def generate_json(lang, strings):
    json_map = {}
    for key in sorted(strings.keys()):
        if lang in strings[key]:
            json_map[key] = _unescape(strings[key][lang])
    return json.dumps(json_map, sort_keys=True, indent='\t')

def main():
    strings = collections.defaultdict(lambda: collections.defaultdict(str))
    
    # Read existing files
    for lang in LANGS:
        parse_lang_file(f'{TEMPLATES_PATH}/{lang}.lang', lang, strings)
        
    # Remove existing badge entries to avoid staleness/duplication if we are re-reading them
    keys_to_remove = [k for k in strings.keys() if k.startswith('badge_')]
    for k in keys_to_remove:
        del strings[k]
        
    # Add badges
    add_badges_entries(strings)
    
    # Generate pseudo
    for key in strings:
        if 'en' in strings[key]:
            strings[key]['pseudo'] = _pseudoloc(strings[key]['en'])
        
    # Write files
    for lang in LANGS + ['pseudo']:
        # Write .lang (sorted)
        with open(f'{TEMPLATES_PATH}/{lang}.lang', 'w', encoding='utf-8') as f:
            f.write(generate_sorted(lang, strings))
            
        # Write .ts
        with open(f'{JS_TEMPLATES_PATH}/lang.{lang}.ts', 'w', encoding='utf-8') as f:
            f.write(generate_typescript(lang, strings))
            
        # Write .json
        with open(f'{JS_TEMPLATES_PATH}/lang.{lang}.json', 'w', encoding='utf-8') as f:
            f.write(generate_json(lang, strings))
    
    print("Successfully regenerated i18n files.")

if __name__ == '__main__':
    main()
